version: "3.8"

services:
  base:
    container_name: PROJECTNAME-base
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
        - USER=${USER:-PROJECTNAME}
    entrypoint: ["npm"]
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    profiles:
      - base
  server:
    container_name: PROJECTNAME-server
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
        - USER=${USER:-PROJECTNAME}
    entrypoint: ["npm"]
    command: ["run", "start:dev"]
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=5001
      - SECRETS_PATH=/secret/data/production/backend
      - VAULT_TOKEN=root
    ports:
      - "5001:5001"
    depends_on:
      - vault
  vault:
    container_name: PROJECTNAME-vault
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server -dev
