version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USER_NAME: ${USER_NAME:-node}
    command: npm run start:dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - CONFIGURATION_FILE=dist/config/development.json
    volumes:
      - .:/home/${USER_NAME}/app
      - ./.npm-cache:/home/${USER_NAME}/.npm
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: development
