version: "3.8"

services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USER_NAME: ${USER_NAME:-node}
    entrypoint: ["npm"]
    command: ["run", "test"]
    environment:
      - CONFIGURATION_FILE=dist/config/test.json
    volumes:
      - .:/home/${USER_NAME}/app
      - node_modules:/home/${USER_NAME}/app/node_modules
      - npm_cache:/home/${USER_NAME}/.npm
    depends_on:
      - test-db
  test-db:
    image: postgres:12.2-alpine
    # start with 5433 port to avoid conflict with the db
    command: ["postgres", "-p", "5433"]
    ports:
      - "5433:5433"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test
volumes:
  test-db-data:
